on:
  push:
    branches:
      - main
      - develop
      - release
      - feature/*
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
        env:
          CI: true
      - name: Generate build
        run: npm run build --if-present

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: clone repository 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}