on:
  push:
    branches:
      - main
      - develop
      - release
      - feature/*
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Create compile
      run: npm run build --if-present
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        path: build
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
    - name: Copy folder content recursively to remote
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "build/"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.SSH_USER }}

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
